package com.example.stocksapp.presentation.details

import com.example.stocksapp.api.responsedto.graph.StockGraphDataItem

data class CompanyOverviewScreenData(
    var symbol: String,
    var assetType: String,
    var name: String,
    var description: String,
    var cik: String,
    var exchange: String,
    var currency: String,
    var country: String,
    var sector: String,
    var industry: String,
    var address: String,
    var officialSite: String,
    var fiscalYearEnd: String,
    var latestQuarter: String,
    var marketCapitalization: String,
    var ebitda: String,
    var PERatio: String,
    var PEGRatio: String,
    var bookValue: String,
    var dividendPerShare: String,
    var dividendYield: String,
    var eps: String,
    var revenuePerShareTTM: String,
    var profitMargin: String,
    var operatingMarginTTM: String,
    var returnOnAssetsTTM: String,
    var returnOnEquityTTM: String,
    var revenueTTM: String,
    var grossProfitTTM: String,
    var dilutedEPSTTM: String,
    var quarterlyEarningsGrowthYOY: String,
    var quarterlyRevenueGrowthYOY: String,
    var analystTargetPrice: String,
    var analystRatingStrongBuy: String,
    var analystRatingBuy: String,
    var analystRatingHold: String,
    var analystRatingSell: String,
    var analystRatingStrongSell: String,
    var trailingPE: String,
    var forwardPE: String,
    var priceToSalesRatioTTM: String,
    var priceToBookRatio: String,
    var EVToRevenue: String,
    var EVToEBITDA: String,
    var beta: String,
    var weekHigh52: String,
    var weekLow52: String,
    var dayMovingAverage50: String,
    var dayMovingAverage200: String,
    var sharesOutstanding: String,
    var dividendDate: String,
    var exDividendDate: String,

    val dailyGraphData: Map<String, StockGraphDataItem>,
    val weeklyGraphData: Map<String, StockGraphDataItem>? = null,
    val monthlyGraphData: Map<String, StockGraphDataItem>? = null
)
